apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment2-app
  namespace: harvir
  labels:
    app: assignment2-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assignment2-app
  template:
    metadata:
      labels:
        app: assignment2-app
    spec:
      containers:
      - name: assignment2-app
        image: harvir/assignment2-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: envValue
          value: "environmentSnake"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: secret-volume
          mountPath: /etc/secret
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      - name: secret-volume
        secret:
          secretName: app-secret
